/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class BodyBulkEnrichCompaniesV0CompaniesBulkEnrichPost extends SpeakeasyBase {
  /**
   * Company names. Will return companies that match these names exactly, case-sensitively.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "companies" })
  companies?: string[];

  /**
   * Company names. Will return companies whose name contain the substrings passed here, case-insensitively.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "companies_fuzzy" })
  companiesFuzzy?: string[];

  /**
   * Company domains, full URLs or emails
   */
  @SpeakeasyMetadata()
  @Expose({ name: "companies_urls" })
  companiesUrls?: string[];
}
