/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class BodyGetTechDetailsV0CompaniesTechDetailsPost extends SpeakeasyBase {
  /**
   * Company names. Will return companies that match these names exactly, case-sensitively.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "companies" })
  companies?: string[];

  /**
   * Company names. Will exclude companies that match these names exactly, case-sensitively.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "companies_exclude" })
  companiesExclude?: string[];

  /**
   * Company domains, full URLs or emails
   */
  @SpeakeasyMetadata()
  @Expose({ name: "companies_urls" })
  companiesUrls?: string[];
}
