/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CompanySimple extends SpeakeasyBase {
  /**
   * ID of the company in Apollo
   */
  @SpeakeasyMetadata()
  @Expose({ name: "apollo_id" })
  apolloId?: string;

  /**
   * Country of the company's HQ
   */
  @SpeakeasyMetadata()
  @Expose({ name: "country" })
  country?: string;

  /**
   * Number of employees of the company
   */
  @SpeakeasyMetadata()
  @Expose({ name: "employee_count" })
  employeeCount?: number;

  /**
   * Industry of the company
   */
  @SpeakeasyMetadata()
  @Expose({ name: "industry" })
  industry?: string;

  /**
   * ID of the company in LinkedIn
   */
  @SpeakeasyMetadata()
  @Expose({ name: "linkedin_id" })
  linkedinId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "linkedin_url" })
  linkedinUrl?: string;

  /**
   * Company name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Number of jobs from this company in our database
   */
  @SpeakeasyMetadata()
  @Expose({ name: "num_jobs" })
  numJobs?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "url" })
  url?: string;

  /**
   * If the company went through YC, this is its batch
   */
  @SpeakeasyMetadata()
  @Expose({ name: "yc_batch" })
  ycBatch?: string;
}
