/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Order by field. Descending
 */
export enum CompanyOrderByEnum {
  EmployeeCount = "employee_count",
  AnnualRevenueUsd = "annual_revenue_usd",
  TotalFundingUsd = "total_funding_usd",
  LastFundingRoundDate = "last_funding_round_date",
  FoundedYear = "founded_year",
  Name = "name",
  Unknown = "",
}
