/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Company } from "./company";
import { CompanySearchMetadata } from "./companysearchmetadata";
import { Expose, Type } from "class-transformer";

/**
 * Successful Response
 */
export class CompaniesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: Company })
  @Expose({ name: "data" })
  @Type(() => Company)
  data?: Company[];

  @SpeakeasyMetadata()
  @Expose({ name: "metadata" })
  @Type(() => CompanySearchMetadata)
  metadata?: CompanySearchMetadata;
}
