/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CompanyTechnology } from "./companytechnology";
import { TechDetailsMetadata } from "./techdetailsmetadata";
import { Expose, Type } from "class-transformer";

/**
 * Successful Response
 */
export class CompanyTechDetailsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: CompanyTechnology })
  @Expose({ name: "data" })
  @Type(() => CompanyTechnology)
  data?: CompanyTechnology[];

  @SpeakeasyMetadata()
  @Expose({ name: "metadata" })
  @Type(() => TechDetailsMetadata)
  metadata?: TechDetailsMetadata;
}
