/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../types";
import { Expose, Transform } from "class-transformer";

export class DecisionMaker extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "company_name" })
  companyName?: string;

  /**
   * Country of the company
   */
  @SpeakeasyMetadata()
  @Expose({ name: "country" })
  country?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "date_posted" })
  @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
  datePosted?: RFCDate;

  @SpeakeasyMetadata()
  @Expose({ name: "decision_maker" })
  decisionMaker?: string;

  /**
   * Number of employees in the company
   */
  @SpeakeasyMetadata()
  @Expose({ name: "employee_count" })
  employeeCount?: number;

  /**
   * Job title of the job post where the decision maker was found
   */
  @SpeakeasyMetadata()
  @Expose({ name: "job_title" })
  jobTitle?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "technology" })
  technology?: string;

  /**
   * URL of the job post
   */
  @SpeakeasyMetadata()
  @Expose({ name: "url" })
  url?: string;
}
