/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../types";
import { Expose, Transform } from "class-transformer";

export class KeywordFound extends SpeakeasyBase {
  /**
   * Category of the technology
   */
  @SpeakeasyMetadata()
  @Expose({ name: "category" })
  category?: string;

  /**
   * Date when the keyword was first mentioned by the company in a job post
   */
  @SpeakeasyMetadata()
  @Expose({ name: "first_date_found" })
  @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
  firstDateFound?: RFCDate;

  /**
   * Number of jobs found mentioning this technology
   */
  @SpeakeasyMetadata()
  @Expose({ name: "jobs" })
  jobs?: number;

  /**
   * Number of jobs from the given company mentioning this technology in the last 180 days
   */
  @SpeakeasyMetadata()
  @Expose({ name: "jobs_last_180_days" })
  jobsLast180Days?: number;

  /**
   * Number of jobs from the given company mentioning this technology in the last 30 days
   */
  @SpeakeasyMetadata()
  @Expose({ name: "jobs_last_30_days" })
  jobsLast30Days?: number;

  /**
   * Number of jobs from the given company mentioning this technology in the last 7 days
   */
  @SpeakeasyMetadata()
  @Expose({ name: "jobs_last_7_days" })
  jobsLast7Days?: number;

  /**
   * Date when the keyword was last mentioned by the company in a job post
   */
  @SpeakeasyMetadata()
  @Expose({ name: "last_date_found" })
  @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
  lastDateFound?: RFCDate;

  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * Measures how common this technology is among the company's jobs, compared to other technologies in the same category. The most mentioned technology in its category will have a rank of 1. This helps you infer which is the technology the company is most likely to be using, when they mention several technologies that belong to the same category.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "rank_within_category" })
  rankWithinCategory?: number;

  /**
   * Measures the relative occurance of this technology among other technologies in the same category, in jobs by this company. If there are 10 jobs where a company mentions 3 categories, and they appear in 8, 3 and 2 jobs respectively, its relative occurrences will be 0.8, 0.3 and 0.2. This helps you infer how likely it is that the company is using this technology, when they mention several technologies that belong to the same category.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "relative_occurrence_within_category" })
  relativeOccurrenceWithinCategory?: number;

  /**
   * This is a score we assign to every technology used by each company to asses how likely it is that they're using it, combining the value of `jobs` and `relative_occurrence_within_category`. The higher this value is, the higher the chances that the company uses this technology. Values lower than 1 mean it's not very likely they use it. Then, the higher the value of theirstack_score, the more likely it is that they actually use it.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "theirstack_score" })
  theirstackScore?: number;
}
