/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Format of the response. One of `json` or `csv`. Defaults to `json`.
 */
export enum ResponseFormatEnum {
  Json = "json",
  Csv = "csv",
}
