/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class Security extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "security, scheme=true;type=apiKey;subtype=cookie;name=theirstack_token",
  })
  apiKeyCookie?: string;

  @SpeakeasyMetadata({
    data: "security, scheme=true;type=apiKey;subtype=query;name=token",
  })
  apiKeyQuery?: string;

  @SpeakeasyMetadata({
    data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
  })
  bearer?: string;

  @SpeakeasyMetadata({
    data: "security, scheme=true;type=oauth2;name=Authorization",
  })
  oAuth2PasswordBearer?: string;
}
