/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

/**
 * Format of the response. One of `json` or `csv`. Defaults to `json`.
 */
export enum BulkEnrichCompaniesV0CompaniesBulkEnrichPostFormatFormatEnum {
  Json = "json",
  Csv = "csv",
}

export class BulkEnrichCompaniesV0CompaniesBulkEnrichPostRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  bodyBulkEnrichCompaniesV0CompaniesBulkEnrichPost?: shared.BodyBulkEnrichCompaniesV0CompaniesBulkEnrichPost;

  /**
   * Format of the response. One of `json` or `csv`. Defaults to `json`.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=format",
  })
  format?: BulkEnrichCompaniesV0CompaniesBulkEnrichPostFormatFormatEnum;
}

export class BulkEnrichCompaniesV0CompaniesBulkEnrichPostResponse extends SpeakeasyBase {
  /**
   * Successful Response
   */
  @SpeakeasyMetadata({ elemType: shared.CompanyWithTechnologies })
  companyWithTechnologies?: shared.CompanyWithTechnologies[];

  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Validation Error
   */
  @SpeakeasyMetadata()
  httpValidationError?: shared.HTTPValidationError;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
