/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as utils from "../internal/utils";
import { Companies } from "./companies";
import { DecisionMakers } from "./decisionmakers";
import { Jobs } from "./jobs";
import * as shared from "./models/shared";
import { Technologies } from "./technologies";
import { Users } from "./users";
import axios from "axios";
import { AxiosInstance } from "axios";

/**
 * Contains the list of servers available to the SDK
 */
export const ServerList = ["https://api.theirstack.com"] as const;

/**
 * The available configuration options for the SDK
 */
export type SDKProps = {
  /**
   * The security details required to authenticate the SDK
   */
  security?: shared.Security;
  /**
   * Allows overriding the default axios client used by the SDK
   */
  defaultClient?: AxiosInstance;
  /**
   * Allows overriding the default server URL used by the SDK
   */
  serverURL?: string;
};

/**
 *
 * @remarks
 *
 * ## Introduction
 *
 * This is [TheirStack.com](https://TheirStack.com) API. [Create an account here](https://theirstack.com/signup).
 *
 * This documentation has two versions. You can open it [in Swagger](/openapi):
 *
 * <a href="/openapi"><img src="/img/swagger-logo-horizontal.jpeg" alt="Open in Swagger" width="200" /></a>
 *
 * And you can open it also [in ReDoc](/) (the default when you visit [api.theirstack.com](https://api.theirstack.com))
 *
 * <a href="/"><img src="/img/redoc-logo.png" alt="Open in ReDoc" width="200" /></a>
 *
 * <br/>
 *
 * ### What is TheirStack?
 *
 * It's a platform that enables market research based on attributes like
 * - what roles companies are hiring for
 * - what technologies companies are using
 * - what are all the companies using any given technologies
 * - what are the jobs from companies fitting certain criteria
 * - what are some companies with N number of people in a given department
 *
 * And much more, letting you filter by countries, industries, cities, etc.
 *
 * ## Who is TheirStack for?
 *
 * If you're building a SaaS with integrations with other products, you can use our API to find companies using them. Or to enrich your signups and know the stack of the companies that sign up for your product.
 *
 * If you're a recruiting agency, you can use Theirstack to know what companies are growing the most and may need help hiring.
 *
 * Or if you're an investor, you may want to know the companies hiring the most people in your country. We have that data as well
 *
 *
 *
 *
 * ## Credits and billing
 * One credit equals one new company returned from our API. You don't consume credits if you retrieve the same company more than once. To control whether you fetch new companies or not, you can use the `new_companies` parameter.
 *
 * Users on the free plan have 20 credits per billing cycle, and can only see the first 5 results for each endpoint. They can use all the parameters for all the endpoints.
 *
 * To know how many credits you have left, check your limits with the [`/users/me`](/#operation/Current_user_details_users_me_get) endpoint.
 *
 * Paid users have more credits and can see as many results as they want paginated endpoints, with the `page` and `limit` parameters.
 *
 *
 * ### Upgrading your plan
 *
 * To upgrade to a plan with higher limits, [shoot us an email](mailto:xoel@theirstack.com) or book a demo with our founder [here](https://calendly.com/xoel-1/theirstack).
 *
 *
 *
 * # Authentication
 *
 * After calling the `/signup` or `/token` endpoints, you get a short-lived Bearer token. Also, when you sign up, a non-expiring Bearer token is automatically generated for you. To see it, make a request to /users/me.
 *
 * Then, you can use any of those tokens to access the API. You can pass the token as a Bearer header, as a cookie (named `token`) or as a query parameter also named `token`.
 *
 *
 */
export class SDK {
  /**
   * Operations with companies
   */
  public companies: Companies;
  /**
   * Finding decision makers
   */
  public decisionMakers: DecisionMakers;
  /**
   * Operations with jobs
   */
  public jobs: Jobs;
  /**
   * To browse the technologies we track
   */
  public technologies: Technologies;
  /**
   * Get info on your account's users
   */
  public users: Users;

  public _defaultClient: AxiosInstance;
  public _securityClient: AxiosInstance;
  public _serverURL: string;
  private _language = "typescript";
  private _sdkVersion = "2.0.2";
  private _genVersion = "2.18.1";
  private _globals: any;

  constructor(props?: SDKProps) {
    this._serverURL = props?.serverURL ?? ServerList[0];

    this._defaultClient =
      props?.defaultClient ?? axios.create({ baseURL: this._serverURL });
    if (props?.security) {
      let security: shared.Security = props.security;
      if (!(props.security instanceof utils.SpeakeasyBase))
        security = new shared.Security(props.security);
      this._securityClient = utils.createSecurityClient(
        this._defaultClient,
        security
      );
    } else {
      this._securityClient = this._defaultClient;
    }

    this.companies = new Companies(
      this._defaultClient,
      this._securityClient,
      this._serverURL,
      this._language,
      this._sdkVersion,
      this._genVersion
    );

    this.decisionMakers = new DecisionMakers(
      this._defaultClient,
      this._securityClient,
      this._serverURL,
      this._language,
      this._sdkVersion,
      this._genVersion
    );

    this.jobs = new Jobs(
      this._defaultClient,
      this._securityClient,
      this._serverURL,
      this._language,
      this._sdkVersion,
      this._genVersion
    );

    this.technologies = new Technologies(
      this._defaultClient,
      this._securityClient,
      this._serverURL,
      this._language,
      this._sdkVersion,
      this._genVersion
    );

    this.users = new Users(
      this._defaultClient,
      this._securityClient,
      this._serverURL,
      this._language,
      this._sdkVersion,
      this._genVersion
    );
  }
}
